server:
  port: 8901

spring:
  profiles:
    active: dev

nginx:
  server_name: 192.168.31.251

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/config/mybatis-config.xml
